INSERT INTO CLIENT_FILE (CLIENT_NUMBER, CLIENT_DATE_OF_BIRTH, CLIENT_NAME, CLIENT_PESEL, CLIENT_SURNAME)
VALUES (1, NOW(), 'Sylwek', '987456321', 'Macura');
INSERT INTO BRA_ACCOUNT (BRA_ACCOUNT_ID, BRA_AVALIBLE_CASH, BRA_BLOCK_CASH, BRA_CLIENT_FILE_ID)
VALUES (1, 200.0, 10, 0, 1);
INSERT INTO INSTRUMENT_DEFINITION (INSTRUMENT_ISIN, INSTRUMENT_DEFINITION_NAME) VALUES ('KGHM', 'KGHM Polska Miedz');
INSERT INTO INSTRUMENT_DEFINITION (INSTRUMENT_ISIN, INSTRUMENT_DEFINITION_NAME)
VALUES ('JSW', 'Jastzrębska Spolka weglowa');
INSERT INTO INSTRUMENT_INFO (INSTR_INFO_AMMOUNT, INSTR_INFO_BLOCKED, INSTR_INFO_BRA_ACCOUNT, INSTR_INFO_DEFINITION)
VALUES (20.0, 0.0, 1, 'KGHM');
INSERT INTO MARKET (MARKET_CODE, MARKET_ACTIVE, MARKET_NAME) VALUES ('GPW', TRUE, 'Gielda papierow wartosciowych');
INSERT INTO INSTRUMENT_MARKET (INSTRUMENT_MARKET_BUY_PRICE, INSTRUMENT_MARKET_SELL_PRICE, INSTRUMENT_MARKET_INSTRUMENT, INSTRUMENT_MARKET_MARKET)
VALUES (19.0, 20.0, 'KGHM', 'GPW');
INSERT INTO INSTRUMENT_MARKET (INSTRUMENT_MARKET_BUY_PRICE, INSTRUMENT_MARKET_SELL_PRICE, INSTRUMENT_MARKET_INSTRUMENT, INSTRUMENT_MARKET_MARKET)
VALUES (9.0, 10.0, 'JSW', 'GPW');


