insert into INSTRUMENT_DEFINITION(INSTRUMENT_ISIN,INSTRUMENT_DEFINITION_NAME) VALUE ('KGHM','KGHM Polska Miedź');
insert into INSTRUMENT_DEFINITION(INSTRUMENT_ISIN,INSTRUMENT_DEFINITION_NAME) VALUE ('JSW','Jastrzębska Spółka Węglowa');

insert into MARKET(MARKET_CODE, MARKET_ACTIVE, MARKET_NAME) VALUES ('GPW',1,'Giełda papierów wartościowych');
insert into MARKET(MARKET_CODE, MARKET_ACTIVE, MARKET_NAME) VALUES ('NYSE',1,'New York Stock Exchange');

INSERT INTO INSTRUMENT_MARKET(INSTRUMENT_MARKET_BUY_PRICE, INSTRUMENT_MARKET_SELL_PRICE, INSTRUMENT_MARKET_INSTRUMENT, INSTRUMENT_MARKET_MARKET) VALUE (20.0,21.0,'KGHM','GPW');
INSERT INTO INSTRUMENT_MARKET(INSTRUMENT_MARKET_BUY_PRICE, INSTRUMENT_MARKET_SELL_PRICE, INSTRUMENT_MARKET_INSTRUMENT, INSTRUMENT_MARKET_MARKET) VALUE (15.0,18.0,'JSW','GPW');